doctrine:
    dbal:
        driver: "pdo_pgsql"
        host: "%env(DATABASE_HOST)%"
        port: "%env(DATABASE_PORT)%"
        dbname: "%env(DATABASE_NAME)%"
        user: "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASSWORD)%"
        server_version: "16"
        charset: utf8
        profiling_collect_backtrace: "%kernel.debug%"
        use_savepoints: true

        # Filter to ignore Supabase schemas
        schema_filter: ~^(?!auth|storage|realtime|graphql|information_schema|pg_|supabase)~

        # Use only public schema
        default_table_options:
            schema: public
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType

        # PostgreSQL-specific type mappings
        mapping_types:
            code_challenge_method: string
            regclass: string
            regrole: string
            _text: string
            _user_defined_filter: string
            _aclitem: string
            _bool: string
            _char: string
            _cidr: string
            _date: string
            _float4: string
            _float8: string
            _inet: string
            _int2: string
            _int4: string
            _int8: string
            _interval: string
            _json: string
            _jsonb: string
            _money: string
            _name: string
            _numeric: string
            _oid: string
            _oidvector: string
            _path: string
            _point: string
            _polygon: string
            _refcursor: string
            _time: string
            _timestamp: string
            _timestamptz: string
            _timetz: string
            _uuid: string
            _varchar: string
            _xid: string
            _xml: string
            aal_level: string
            factor_type: string
            factor_status: string
            one_time_token_type: string
            pg_lsn: string
            pg_snapshot: string
            txid_snapshot: string
            unknown: string

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false

        # Configuration du cache Doctrine
        metadata_cache_driver:
            type: pool
            pool: doctrine.metadata_cache
        query_cache_driver:
            type: pool
            pool: doctrine.query_cache
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache

        # Cache de second niveau (L2) pour les entités
        second_level_cache:
            enabled: true
            region_cache_driver:
                type: pool
                pool: doctrine.result_cache

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
